arch: deeplabv3
encoder: resnet50
gpu: 0
workers: 8
nfold: 2
batch-size: 32
val-batch-size: 512
epochs: 1
train-data: /homes/oester/repositories/prae/data/segmentation/preprocessed/train/HEEL_d16_train
label-map-file: /homes/oester/repositories/prae/data/segmentation/label_map.json
patch-label-type: mask
draw-patches-per-class: 100
vali-split: 0.2
learning-rate: 0.0001
lr-gamma: 0.95
adjust-lr: true
merge-classes: [[10,7]] # cortex, cortex_atrophy
image-label-in-path: false
normalize: true
logdir: logdir_sem_seg/d16_deeplab
evaluate-every: 10
warm-up-epochs: 0
early-stopping-epochs: 10
criterion: 'cross_entropy'
n-eval-wsis: 10
overlay-polygons: true
use-ln: true
log-details: false
seed: 13
performance-metric: loss
attention-on: false
sample-size: 5