arch: deeplabv3
encoder: resnet50
gpu: 2
workers: 8
nfold: 2
batch-size: 32
val-batch-size: 256
epochs: 3
train-data: /homes/oester/repositories/prae/data/segmentation/preprocessed/train/HEEL_d16_train
label-map-file: /homes/oester/repositories/prae/data/segmentation/label_map.json
patch-label-type: mask
draw-patches-per-class: 100
vali-split: 0.2
learning-rate: 0.0001
lr-gamma: 0.95
adjust-lr: true
merge-classes: [[10,7]] # cortex, cortex_atrophy
image-label-in-path: false
normalize: true
logdir: logdir_sem_seg/a_d16_k8_deeplab_test
evaluate-every: 1
warm-up-epochs: 0
early-stopping-epochs: 10
criterion: 'cross_entropy'
use-ce-weights: false
n-eval-wsis: 1
overlay-polygons: true
embedding-dim: 1024
k-neighbours: 8
use-ln: true
use-pos-encoding: true
learn-pos-encoding: false
num-attention-heads: 8
attention-hidden-dim: 1024
use-self-attention: false
log-details: true
memory-to-gpu: true
seed: 13
performance-metric: dice
attention-on : true
sample-size: 5