test-data: /homes/oester/repositories/prae/data/segmentation/preprocessed/w163_d16
reload-model-folder: logdir_paper/configs_paper/configs_rcc/attention/deeplab_res50/variants/a_d16_k8_deeplab_helperloss08_config-2022-08-18_02_03_14_3
#include-val-inference: True
gpu: 5
sample-size: 10