test-data: /homes/oester/repositories/prae/data/segmentation/preprocessed/q
reload-model-folder: logdir_paper/configs_paper/configs_cy16/multiscale/d2_c8_deeplab_config-2022-09-13_07_56_36_5
gpu: 2
folds: [3]