arch: deeplabv3
encoder: resnet50
gpu: 5
workers: 8
batch-size: 32
val-batch-size: 256
epochs: 200
test-data: /homes/oester/repositories/prae/data/segmentation/preprocessed/test/HEEL_d16_test
train-data: /homes/oester/repositories/prae/data/segmentation/preprocessed/train/HEEL_d16_train
label-map-file: /homes/oester/repositories/prae/data/segmentation/label_map.json
patch-label-type: mask
draw-patches-per-class: 100
vali-split: 0.2
learning-rate: 0.0001
lr-gamma: 0.95
adjust-lr: true
merge-classes: [[10,7]] # cortex, cortex_atrophy
image-label-in-path: false
normalize: true
augment: false
logdir: logdir_test/a_d16_k8_deeplab_vit_d2_h8
evaluate-every: 0
warm-up-epochs: 5
early-stopping-epochs: 10
criterion: 'cross_entropy'
use-ce-weights: false
n-eval-wsis: 10
overlay-polygons: true
embedding-dim: 512
k-neighbours: 8
use-ln: true
use-pos-encoding: true
learn-pos-encoding: false
num-attention-heads: 8
transformer-depth: 2
mlp-hidden-dim: 512
attention-hidden-dim: 256
use-self-attention: false
log-details: false
memory-to-gpu: true
seed: 13
performance-metric: loss
attention-on : true
use-transformer: true