arch: unet
encoder: resnet50
gpu: 5
workers: 0
batch-size: 2
val-batch-size: 2
test-batch-size: 200
epochs: 2
train-data: /homes/oester/repositories/prae/data/segmentation/preprocessed/train/HEEL_d128_debug
#test-data: /homes/oester/repositories/prae/data/segmentation/preprocessed/test/HEEL_d128_test 
#reload-model-folder: /homes/oester/repositories/prae/logdir_test/attention_segmentation-2022-02-08_15_07_53
label-map-file: /homes/oester/repositories/prae/data/segmentation/label_map.json
patch-label-type: mask
draw-patches-per-class: 50
vali-split: 0.5
learning-rate: 0.00002
merge-classes: [[10,7]] # cortex, cortex_atrophy
adjust-lr: true
lr-gamma: 0.95
image-label-in-path: false
normalize: true
logdir: logdir_test
evaluate-every: 2
#warm-up-epochs: 5
early-stopping-epochs: 10
criterion: 'cross_entropy'
use-ce-weights: true
n-eval-wsis: 10
overlay-polygons: true
embedding-dim: 1024
k-neighbours: 0
use-ln: true
use-pos-encoding: true
learn-pos-encoding: false
num-attention-heads: 8
attention-hidden-dim: 1024
use-self-attention: true
log-details: false
memory-to-gpu: true
seed: 13
performance-metric: loss
attention-on: false
multiscale-on: true