test-data: /homes/oester/repositories/prae/data/segmentation/preprocessed/test/HEEL_d8_test
reload-model-folder: /homes/oester/repositories/prae/logdir_sem_seg/d8_unet_resnet18/attention_segmentation-2022-02-17_10_48_17
include-val-inference: False
gpu: 0