arch: deeplabv3
encoder: resnet50
gpu: 1
workers: 8
batch-size: 32
val-batch-size: 256
epochs: 20
train-data: /homes/oester/repositories/prae/data/segmentation/preprocessed/train/HEEL_d128_debug
label-map-file: /homes/oester/repositories/prae/data/segmentation/label_map.json
patch-label-type: mask
draw-patches-per-class: 100
vali-split: 0.2
learning-rate: 0.0001
lr-gamma: 0.95
adjust-lr: true
merge-classes: [[10,7]] # cortex, cortex_atrophy
image-label-in-path: false
normalize: true
augment: true
logdir: logdir_test/a_d128_deeplab
evaluate-every: 0
warm-up-epochs: 1
early-stopping-epochs: 10
criterion: 'cross_entropy'
n-eval-wsis: 10
overlay-polygons: true
embedding-dim: 1024
k-neighbours: 4
use-ln: true
use-pos-encoding: true
learn-pos-encoding: false
num-attention-heads: 8
attention-hidden-dim: 1024
use-self-attention: false
log-details: true
memory-to-gpu: true
seed: 13
performance-metric: loss
attention-on : true