arch: unet
encoder: resnet18
gpu: 4
workers: 8
batch-size: 32
val-batch-size: 64
epochs: 200
include-val-inference: False
reload-model-folder: /homes/oester/repositories/prae/logdir_sem_seg/context_d8_c32/attention_segmentation-2022-02-27_15_54_12
test-data: /homes/oester/repositories/prae/data/segmentation/preprocessed/test/HEEL_d8_context32_test
train-data: /homes/oester/repositories/prae/data/segmentation/preprocessed/train/HEEL_d8_context32_train
label-map-file: /homes/oester/repositories/prae/data/segmentation/label_map.json  
patch-label-type: mask
draw-patches-per-class: 100
vali-split: 0.2
learning-rate: 0.0001
lr-gamma: 0.975
adjust-lr: true
merge-classes: [[10,7]] # cortex, cortex_atrophy
image-label-in-path: false
normalize: true
logdir: logdir_sem_seg/context_d8_c32
evaluate-every: 0
warm-up-epochs: 5
early-stopping-epochs: 10
criterion: 'cross_entropy'
use-ce-weights: false
n-eval-wsis: 10
overlay-polygons: true
embedding-dim: 1024
k-neighbours: 16
use-ln: true
use-pos-encoding: true
learn-pos-encoding: false
num-attention-heads: 8
attention-hidden-dim: 1024
use-self-attention: false
log-details: false
memory-to-gpu: true
seed: 13
performance-metric: loss
attention-on : false
multiscale-on: true