arch: unet
encoder: resnet50
ngpus: 5
workers: 0
batch-size: 32
val-batch-size: 512
epochs: 200
train-data: /homes/oester/repositories/prae/data/segmentation/preprocessed/train/HEEL_d16_train
label-map-file: /homes/oester/repositories/prae/data/segmentation/label_map.json
patch-label-type: mask
draw-patches-per-class: 100
#vali-split: 0.2
nfold: 5
learning-rate: 0.0001
merge-classes: [[10,7]] # cortex, cortex_atrophy
adjust-lr: false
image-label-in-path: false
normalize: true
logdir: logdir_sem_seg/a_d16_k4/cv
evaluate-every: 10
warm-up-epochs: 5
early-stopping-epochs: 10
criterion: 'cross_entropy'
n-eval-wsis: 10
overlay-polygons: true
attention-on: true
embedding-dim: 1024
k-neighbours: 4
use-ln: true
use-pos-encoding: true
learn-pos-encoding: false
num-attention-heads: 8
attention-hidden-dim: 1024
use-self-attention: false
log-details: false
memory-to-gpu: true
seed: 13
performance-metric: loss