arch: resnet50
gpu: 1
ngpus: 6
workers: 16
batch-size: 1 # must be one!
epochs: 100
train-data: /homes/oester/repositories/prae/data/preprocessed_test/PDL1
embedding-data: /homes/oester/repositories/prae/logdir_embedding/embedding-2021-11-22_09_28_25_pdl1_1024/compressed_wsis
label-map-file: /homes/oester/repositories/prae/data/preprocessed/label_map.json
patch-label-type: image
#exclude-classes: [-1, 1] #, 10, 18]
include-classes: [9] # tumor vital
vali-split: 0.5
dim: 1024
#nfold: 2
mc-runs: 3
learning-rate: 0.001
beta1: 0.9
beta2: 0.9999
k-sample: 8
#patch-sampling: under
pretrained: true
image-label-in-path: true
#draw-patches-per-class: 500
weight-decay: 0.1
rnd-embedding-ratio: 0.5
adjust-lr: false
bag_weight: 0.7 # paper
logdir: logdir_clam_test
#reload-model-folder: /homes/oester/repositories/prae/logdir/_favorites/supervised-2021-11-08_09_36_32_treatment_outcome_class_8_without_norm_PDL1