arch: resnet50
workers: 16
batch-size: 32
val-batch-size: 48
epochs: 10
train-data: /homes/oester/repositories/prae/data/segmentation/preprocessed/HEEL_test
label-map-file: /homes/oester/repositories/prae/data/segmentation/label_map.json
patch-label-type: mask
draw-patches-per-class: 500
merge-classes: [[10, 7]]
vali-split: 0.5
learning-rate: 0.0001
adjust-lr: true
pretrained: true
image-label-in-path: false
dropout: false
freeze: false
normalize: true
logdir: logdir_contrastive
evaluate-every: 1
warm-up-epochs: 0
early-stopping-epochs: 5
criterion: 'cross_entropy'
overlay-polygons: true


