arch: resnet50
gpu: 4
workers: 16
batch-size: 32
val-batch-size: 48
epochs: 200
train-data: /homes/oester/repositories/prae/data/segmentation/preprocessed/HEEL_seg_masks_lbl_downsample_8
label-map-file: /homes/oester/repositories/prae/data/segmentation/label_map.json
patch-label-type: mask
draw-patches-per-class: 500
vali-split: 0.2
learning-rate: 0.00002
adjust-lr: false
image-label-in-path: false
normalize: true
logdir: logdir_contrastive
evaluate-every: 10
warm-up-epochs: 5
early-stopping-epochs: 10
criterion: 'cross_entropy'
overlay-polygons: true
