arch: resnet50
gpu: 5
workers: 16
batch-size: 32
val-batch-size: 256
epochs: 10
train-data: /homes/oester/repositories/prae/data/segmentation/preprocessed/HEEL_test_8
label-map-file: /homes/oester/repositories/prae/data/segmentation/label_map.json
patch-label-type: mask
#draw-patches-per-class: 100
vali-split: 0.5
learning-rate: 0.00002
merge-classes: [[10,7]] # cortex, cortex_atrophy
adjust-lr: false
image-label-in-path: false
normalize: true
logdir: logdir_test/d128
evaluate-every: 1
warm-up-epochs: 5
early-stopping-epochs: 10
criterion: 'cross_entropy'
n-eval-wsis: 10
overlay-polygons: true
seed: 13