arch: resnet50
gpu: 2
workers: 16
batch-size: 32
epochs: 100
train-data: /homes/oester/repositories/prae/data/segmentation/preprocessed/HEEL_seg_masks_lbl
label-map-file: /homes/oester/repositories/prae/data/segmentation/label_map.json
vali-split: 0.2
learning-rate: 0.0001
draw-patches-per-class: 50
overlay-polygons: true
pretrained: true
patch-label-type: distribution
image-label-in-path: false
dropout: false
freeze: false
normalize: true
logdir: logdir_dist
evaluate-every: 10
warm-up-epochs: 5
early-stopping-epochs: 10