test-data: /homes/oester/repositories/prae/data/segmentation/preprocessed/test/HEEL_d8_context32_test
reload-model-folder: /homes/oester/repositories/prae/logdir_sem_seg/context_d8_c32/attention_segmentation-2022-02-27_15_54_12
include-val-inference: False
gpu: 3