arch: deeplabv3
encoder: resnet50
#gpus: [1,2,3,4,5]
gpu: 5
workers: 4
batch-size: 32
val-batch-size: 256
epochs: 200
#include-val-inference: True
#reload-model-folder: /homes/oester/repositories/valuingvicinity/logdir_test/a_camelyon_d16_deeplab_resnet18_k8/attention_segmentation-2022-03-04_10_54_57
train-data: /homes/oester/repositories/prae/data/segmentation/preprocessed/train/CAMELYON_d4_train
label-map-file: /homes/oester/repositories/prae/data/segmentation/label_map_camelyon.json
patch-label-type: mask
draw-patches-per-class: 100
#nfold: 5
vali-split: 0.2
learning-rate: 0.0001
lr-gamma: 0.95
adjust-lr: true
image-label-in-path: false
include-classes: [0,1,2]
normalize: true
augment: false
logdir: logdir_test/a_camelyon_d4_deeplab_k8_emb2048
evaluate-every: 0
warm-up-epochs: 5
early-stopping-epochs: 10
criterion: 'cross_entropy'
use-ce-weights: false
n-eval-wsis: 4
overlay-polygons: true
embedding-dim: 2048
k-neighbours: 8
use-ln: true
use-pos-encoding: true
learn-pos-encoding: false
num-attention-heads: 8
attention-hidden-dim: 1024
use-self-attention: false
log-details: true
memory-to-gpu: true
seed: 13
performance-metric: loss
attention-on : true
multiscale-on: false
use_transformer: true