arch: deeplabv3
encoder: resnet18
gpu: 5
workers: 0
batch-size: 32
val-batch-size: 256
epochs: 200
include-val-inference: True
train-data: /homes/oester/repositories/prae/data/segmentation/preprocessed/train/CAMELYON_d16_train
label-map-file: /homes/oester/repositories/prae/data/segmentation/label_map_camelyon.json
patch-label-type: mask
draw-patches-per-class: 100
vali-split: 0.2
learning-rate: 0.0001
lr-gamma: 0.95
adjust-lr: true
image-label-in-path: false
include-classes: [0,1,2]
normalize: true
logdir: logdir_test/a_camelyon_d16_deeplab_resnet18_k8
evaluate-every: 0
warm-up-epochs: 5
early-stopping-epochs: 10
criterion: 'cross_entropy'
use-ce-weights: false
n-eval-wsis: 4
overlay-polygons: true
embedding-dim: 1024
k-neighbours: 16
use-ln: true
use-pos-encoding: true
learn-pos-encoding: false
num-attention-heads: 8
attention-hidden-dim: 1024
use-self-attention: false
log-details: false
memory-to-gpu: true
seed: 13
performance-metric: loss
attention-on : true
multiscale-on: false