arch: unet
encoder: resnet18
gpu: 2
workers: 8
nfold: 5
batch-size: 32
val-batch-size: 256
epochs: 100
train-data: /homes/oester/repositories/prae/data/segmentation/preprocessed/train/CAMELYON_d8_train
label-map-file: /homes/oester/repositories/prae/data/segmentation/label_map_camelyon.json
include-classes: [0,1,2]
patch-label-type: mask
draw-patches-per-class: 100
vali-split: 0.2
learning-rate: 0.0001
lr-gamma: 0.95
adjust-lr: true
image-label-in-path: false
normalize: true
logdir: logdir_paper
evaluate-every: 0
n-eval-wsis: 5
warm-up-epochs: 5
early-stopping-epochs: 10
criterion: 'cross_entropy'
use-ce-weights: false
overlay-polygons: true
embedding-dim: 1024
k-neighbours: 8
use-ln: true
emb-dropout: 0
att-dropout: 0
sin-pos-encoding: true
learn-pos-encoding: false
num-attention-heads: 8
attention-hidden-dim: 1024
use-self-attention: false
log-details: false
seed: 13
augment: true
performance-metric: loss
attention-on: true
helper-loss: true
combine-weight: 0.8
