arch: unet
encoder: resnet18
gpu: 2
workers: 8
#nfold: 5
batch-size: 32
val-batch-size: 256
epochs: 2
train-data: /homes/oester/repositories/prae/data/segmentation/preprocessed/train/HEEL_d128_train
label-map-file: /homes/oester/repositories/prae/data/segmentation/label_map.json
patch-label-type: mask
draw-patches-per-class: 100
vali-split: 0.2
learning-rate: 0.0001
lr-gamma: 0.95
adjust-lr: true
merge-classes: [[10,7]] # cortex, cortex_atrophy
image-label-in-path: false
normalize: true
logdir: logdir_paper/d128_deeplab_res18
evaluate-every: 0
n-eval-wsis: 5
warm-up-epochs: 0
early-stopping-epochs: 10
criterion: 'cross_entropy'
use-ce-weights: false
overlay-polygons: true
log-details: true
seed: 13
performance-metric: loss
attention-on: false
sample-size: 3